[tool.ruff]
target-version = "py311"
line-length = 88
fix = true

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "N"]
ignore = ["E501"]

[tool.ruff.lint.isort]
known-first-party = ["schedule_telegram_bot"]

