"""Update events table

Revision ID: 8c80bc7cdbf0
Revises: c4d31ce2329b
Create Date: 2026-01-21 12:14:45.614016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c80bc7cdbf0'
down_revision: Union[str, Sequence[str], None] = 'c4d31ce2329b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('events', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('events', sa.Column('start_datetime', sa.DateTime(), nullable=False))
    op.add_column('events', sa.Column('end_datetime', sa.DateTime(), nullable=True))
    op.add_column('events', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('events', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('events', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('events', 'day')
    op.drop_column('events', 'event')
    op.drop_column('events', 'time')
    op.alter_column('users', 'first_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=False)
    op.add_column('events', sa.Column('time', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('event', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('day', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('events', 'updated_at')
    op.drop_column('events', 'created_at')
    op.drop_column('events', 'status')
    op.drop_column('events', 'end_datetime')
    op.drop_column('events', 'start_datetime')
    op.drop_column('events', 'description')
    op.drop_column('events', 'title')
    # ### end Alembic commands ###
